import{i as m,a as b,S as w}from"./assets/vendor-da186403.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))n(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&n(i)}).observe(document,{childList:!0,subtree:!0});function l(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(t){if(t.ep)return;t.ep=!0;const o=l(t);fetch(t.href,o)}})();const u=document.querySelector(".form"),g=document.querySelector(".gallery"),r=document.querySelector(".load-btn"),a=document.querySelector(".loader");let p,d=1,c;u.addEventListener("submit",v);r.addEventListener("click",S);async function v(s){s.preventDefault(),g.innerHTML="",a.classList.remove("hidden"),r.classList.add("hidden"),c=u.elements.q.value.trim(),d=1;try{if(c!==""){const e=await h(c);e.hits.length===0?m.show({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",backgroundColor:"#EF4040",titleColor:"#FFFFFF",messageColor:"#FFFFFF"}):(f(e.hits),r.classList.remove("hidden"))}else m.show({message:"Please fill out the search field",position:"topRight",backgroundColor:"#EF4040",titleColor:"#FFFFFF",messageColor:"#FFFFFF"}),a.classList.add("hidden")}catch(e){console.log(e)}finally{a.classList.add("hidden"),u.reset()}}function C(){const s=document.querySelector(".gallery-item"),{height:e}=s.getBoundingClientRect();return e}async function S(){r.classList.add("hidden"),a.classList.remove("hidden");const s=C();d+=1;try{const e=await h();f(e.hits),r.classList.remove("hidden"),window.scrollBy({top:s*2,left:0,behavior:"smooth"}),e.totalHits-d*40<=0&&(m.show({message:"We're sorry, but you've reached the end of search results.",position:"topRight",backgroundColor:"#03a9f4",titleColor:"#FFFFFF",messageColor:"#FFFFFF"}),r.classList.add("hidden"))}catch(e){console.log(e)}finally{a.classList.add("hidden")}}const h=async function(){const s="42001706-084c655b89d9d100c07cefb17",e="https://pixabay.com/api/";return(await b.get(e,{params:{key:s,q:c,image_type:"photo",orientation:"horizontal",safesearch:"true",page:d,per_page:40}})).data};function f(s){const e=s.map(l=>{const{webformatURL:n,largeImageURL:t,tags:o,likes:i,views:y,comments:F,downloads:L}=l;return`<li class="gallery-item">
                <a class="gallery-link" href=${t}>
                <img src=${n} alt="${o}" /></a>
                    <ul class="image-desc">
                        <li class="image-desc-item"><p>Likes</p><p>${i}</p></li>
                        <li class="image-desc-item"><p>Views</p><p>${y}</p></li>
                        <li class="image-desc-item"><p>Comments</p><p>${F}</p></li>
                        <li class="image-desc-item"><p>Downloads</p><p>${L}</p></li>
                    </ul>
            </li>`});q(e),p.refresh()}function q(s){s=s.join(""),g.insertAdjacentHTML("beforeend",s),p=new w(".gallery a",{captionDelay:250,captionsData:"alt"})}
//# sourceMappingURL=commonHelpers.js.map
