import{a as v,i as u,S as w}from"./assets/vendor-b0e94dfd.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const l of s.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&a(l)}).observe(document,{childList:!0,subtree:!0});function r(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function a(e){if(e.ep)return;e.ep=!0;const s=r(e);fetch(e.href,s)}})();const f=async function(o,t){const r="42001706-084c655b89d9d100c07cefb17",a="https://pixabay.com/api/";return(await v.get(a,{params:{key:r,q:o,image_type:"photo",orientation:"horizontal",safesearch:"true",page:t,per_page:40}})).data},h=(o,t)=>o.map(a=>{const{webformatURL:e,largeImageURL:s,tags:l,likes:y,views:F,comments:L,downloads:b}=a;return`<li class="gallery-item">
                <a class="gallery-link" href=${s}>
                <img src=${e} alt="${l}" /></a>
                    <ul class="image-desc">
                        <li class="image-desc-item"><p>Likes</p><p>${y}</p></li>
                        <li class="image-desc-item"><p>Views</p><p>${F}</p></li>
                        <li class="image-desc-item"><p>Comments</p><p>${L}</p></li>
                        <li class="image-desc-item"><p>Downloads</p><p>${b}</p></li>
                    </ul>
            </li>`}).join(""),p=document.querySelector(".form"),g=document.querySelector(".gallery"),i=document.querySelector(".load-btn"),n=document.querySelector(".loader");let d,c=1,m;p.addEventListener("submit",C);i.addEventListener("click",S);async function C(o){o.preventDefault(),g.innerHTML="",n.classList.remove("hidden"),i.classList.add("hidden"),m=p.elements.q.value.trim(),c=1;try{if(m!==""){const t=await f(m,c);if(t.hits.length===0)u.show({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",backgroundColor:"#EF4040",titleColor:"#FFFFFF",messageColor:"#FFFFFF"});else{const r=h(t.hits,d);g.insertAdjacentHTML("beforeend",r),d.refresh(),i.classList.remove("hidden")}}else u.show({message:"Please fill out the search field",position:"topRight",backgroundColor:"#EF4040",titleColor:"#FFFFFF",messageColor:"#FFFFFF"}),n.classList.add("hidden")}catch(t){console.log(t)}finally{n.classList.add("hidden"),p.reset()}}async function S(){i.classList.add("hidden"),n.classList.remove("hidden"),c+=1;try{const o=await f(m,c),t=h(o.hits,d);g.insertAdjacentHTML("beforeend",t),d.refresh(),i.classList.remove("hidden"),o.totalHits-c*40<=0&&(u.show({message:"We're sorry, but you've reached the end of search results.",position:"topRight",backgroundColor:"#03a9f4",titleColor:"#FFFFFF",messageColor:"#FFFFFF"}),i.classList.add("hidden"))}catch(o){console.log(o)}finally{n.classList.add("hidden")}}document.addEventListener("DOMContentLoaded",()=>{d=new w(".gallery a",{captionDelay:250,captionsData:"alt"})});
//# sourceMappingURL=commonHelpers.js.map
